# Site settings
name: S Shen
description: "Maths & Stats | Linux Newbie | Android Enthusiast | Amature Translator"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
twitter_username: SierraShen
google_plus_username: sshen
# linkedin_username: rkmallik
# lastfm_username: bobathia
# github_username:  rkmallik
# facebook_username: rkmallik
# instagram_username:  rkmallik
# flickr_username: ronakm
telegram_username: S_Shen
steam_username: 76561198101999878
# email: ronak@rkmallik.com

avatar: yes
# avatar_img_path: ""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/13935579"

front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
