# Site settings
name: S Shen
description: "Linux Newbie • Android Enthusiast • Amateur Translator"
url: "s-shen.space"
title: S Shen


# Delete the lines you don't need
# about 5 elements are recomended
twitter_username: iamsshen
google_plus_username: sshen
# linkedin_username: 
# lastfm_username: 
# github_username:  
# facebook_username: 
instagram_username:  iam.sshen
# flickr_username: 
telegram_username: S_Shen
steam_username: 76561198101999878
# email: 

avatar: yes
avatar_img_path: "https://raw.githubusercontent.com/ContactFront/ContactFront.github.io/master/imgs/avatar.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
